FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY BookStoreApi/*.csproj ./BookStoreApi/
COPY BookStoreApi.Tests/*.csproj ./BookStoreApi.Tests/
RUN dotnet restore

# Copy everything else and build
COPY ./BookStoreApi/. ./BookStoreApi/
COPY ./BookStoreApi.Tests/. ./BookStoreApi.Tests/
WORKDIR /app/BookStoreApi.Tests
RUN dotnet build

# Run tests
CMD ["dotnet", "test"]
