version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bookstore_test}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
    ports:
      - "5433:5432"
    volumes:
      - db-test-data:/var/lib/postgresql/data

  test:
    image: bookstoreapi-test:latest
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Testing}
      PostgreSQL__ConnectionString: ${PostgreSQL__ConnectionString:-Host=db;Database=bookstore_test;Username=admin;Password=admin123}
      JwtSettings__Secret: ${JwtSettings__Secret:-Secret123456789000000000000000000000000000}
      JwtSettings__Issuer: ${JwtSettings__Issuer:-BookStoreIssuer}
      JwtSettings__Audience: ${JwtSettings__Audience:-BookStoreAudience}
      JwtSettings__TokenLifetime: ${JwtSettings__TokenLifetime:-120}
      AdminSettings__AdminEmail: ${AdminSettings__AdminEmail:-admin@bookstore.com}
      AdminSettings__AdminPassword: ${AdminSettings__AdminPassword:-Admin@1231}
      AdminSettings__AdminUsername: ${AdminSettings__AdminUsername:-admin}
    depends_on:
      - db

volumes:
  db-test-data:
