version: '3.8'

services:
  bookstoretest:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      ASPNETCORE_ENVIRONMENT: Testing
      JwtSettings__Secret: Secret123456789000000000000000000000000000
      JwtSettings__Issuer: BookStoreIssuer
      JwtSettings__Audience: BookStoreAudience
      JwtSettings__TokenLifetime: 120
      AdminSettings__AdminEmail: admin@bookstore.com
      AdminSettings__AdminPassword: Admin@1231
      AdminSettings__AdminUsername: admin
