FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BookStoreApi.Tests/BookStoreApi.Tests.csproj", "BookStoreApi.Tests/"]
COPY ["BookStoreApi/BookStoreApi.csproj", "BookStoreApi/"]
RUN dotnet restore "BookStoreApi.Tests/BookStoreApi.Tests.csproj"
COPY . .
WORKDIR "/src/BookStoreApi.Tests"
RUN dotnet build "BookStoreApi.Tests.csproj" -c Release -o /app/build

FROM build AS testrunner
WORKDIR /src/BookStoreApi.Tests
ENTRYPOINT ["dotnet", "test", "--logger:trx"]
