name: Build and test with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build Docker image and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test Docker images
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

      - name: Check test result
        run: |
          exit $(docker-compose -f docker-compose.test.yml ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l)
